---
- name: testing ansible
  hosts: all
  become: yes
  tasks:
    - name: copy war file to target server
      copy:
        src:/home/jenkins/jenkins_root/workspace/deployment/webapp/target/webapp.war
        dest: /opt/apache-tomcat-9.0.54/webapps
        remote_src: yes
